# Docker compose overrides for running in dev mode. This mounts local code in
# the running containers, defines some extra containers needed for development,
# etc. This is not a standalone file. It extends docker-compose.yml and
# requires a local recursive clone of the parent git repository.

version: '2.0'

services:
  rabbitmq:
    ports:
      - 15672:15672

  elasticsearch:
    ports:
      - 9200:9200

  vault:
    ports:
      - 8200:8200

  logstash:
    volumes:
      - ./docker/logstash/config:/config-dir:rw

  kibana:
    ports:
      - 5601:5601

  elasticsearch-manage:
    volumes:
      - ./docker/elasticsearch-manage:/opt/elasticsearch-manage

  debugger:
    image: mist/debugger
    volumes:
      - ./keys:/keys

  scheduler: &backend
    volumes:
      - ./defaults.py:$CONF_DIR/defaults.py:ro
      - ./api:/mist.api:rw
      - ./keys:/keys
      - ./orchestration:/opt/orchestration:rw

  hubshell: *backend
  api: *backend
  api-v2: *backend
  sockjs: *backend
  apply-migrations: *backend
  dramatiq: *backend

  ui:
    volumes:
      - ./ui:/ui:rw

  landing:
    volumes:
      - ./landing:/landing:rw
  nginx:
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/nginx-listen.conf:/etc/nginx/nginx-listen.conf:ro
      - ./docker/nginx/static:/srv/www/static:ro

  vminsert:
    image: victoriametrics/vminsert:v1.60.0-cluster
    command:
      - '--influxTrimTimestamp=1s'
      - '--storageNode=vmstorage:8400'
    ports:
      - 8480

  vmstorage:
    image: victoriametrics/vmstorage:v1.60.0-cluster
    command:
      - '--retentionPeriod=12'
      - '--storageDataPath=/var/lib/victoria-metrics-data'
    ports:
      - 8400
      - 8401
      - 8482
    volumes:
      - victoria-metrics:/var/lib/victoria-metrics-data

  vmselect:
    image: victoriametrics/vmselect:v1.60.0-cluster
    command:
      - '--search.latencyOffset=0s'
      - '--search.cacheTimestampOffset=15m'
      - '--storageNode=vmstorage:8401'
      - '--search.maxQueryLen=1GiB'
    ports:
      - 8481

  gocky:
    volumes:
      - ./docker/gocky:/etc/gocky

  influxdb:
    volumes:
      - ./docker/influxdb:/etc/influxdb

