# Docker compose overrides for running in dev mode. This mounts local code in
# the running containers, defines some extra containers needed for development,
# etc. This is not a standalone file. It extends docker-compose.yml and
# requires a local recursive clone of the parent git repository.

version: '2.0'

services:
  elasticsearch:
    ports:
      - 9200:9200

  logstash:
    volumes:
      - ./docker/logstash/config:/config-dir:rw

  kibana:
    ports:
      - 5601:5601

  elasticsearch-manage:
    volumes:
      - ./docker/elasticsearch-manage:/opt/elasticsearch-manage

  debugger:
    image: mist/debugger
    volumes:
      - ./keys:/keys

  celery-prefork: &backend
    volumes:
      - ./defaults.py:$CONF_DIR/defaults.py:ro
      - ./api:/mist.api:rw
      - ./keys:/keys
  celery-gevent: *backend
  scheduler: *backend
  poller: *backend
  cilia: *backend
  beat: *backend
  hubshell: *backend
  api: *backend
  api-v2: *backend
  sockjs: *backend
  apply-migrations: *backend
  dramatiq: *backend

  ui:
    volumes:
      - ./ui:/ui:rw

  landing:
    volumes:
      - ./landing:/landing:rw
  nginx:
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/nginx-listen.conf:/etc/nginx/nginx-listen.conf:ro
      - ./docker/nginx/static:/srv/www/static:ro

  gocky:
    volumes:
      - ./docker/gocky:/etc/gocky

  influxdb:
    volumes:
      - ./docker/influxdb:/etc/influxdb

