# Docker compose overrides for running mist.io in dev mode. This mounts local
# code in the running containers, defines some extra containers needed for
# development, etc. This is not a standalone file. It extends
# docker-compose.yml and requires a local recursive clone of the mist.io git
# repository.

version: '2.0'

services:


  elasticsearch:
    ports:
      - 9200:9200

  kibana:
    ports:
      - 5601:5601

  celery-prefork: &backend
    volumes:
      - ./config/defaults.py:/etc/clearglass/defaults.py:ro
      - ./api:/mist.api:rw
      - ./keys:/keys
      - ./elasticsearch:/elasticsearch
  celery-gevent: *backend
  scheduler: *backend
  poller: *backend
  beat: *backend
  hubshell: *backend
  api: *backend
  sockjs: *backend


  ui:
    volumes:
      - ./ui:/ui:rw

  landing:
    volumes:
      - ./landing:/landing:rw

  debugger:
    image: mist/debugger
    volumes:
      - ./keys:/keys

  nginx:
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx-listen.conf:/etc/nginx/nginx-listen.conf:ro
      - ./static:/srv/www/static
