apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    clearglass.service: api
  name: api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        clearglass.service: api
    spec:
      imagePullSecrets:
{{ toYaml .Values.image.secrets | indent 8 }}
      containers:
      - args:
        - bin/wait-all
        - bin/uwsgi
        image: {{ .Values.image.registry }}/api:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: api
        resources:
          requests:
            memory: 700Mi
            cpu: 500m
          limits:
            memory: 1500Mi
            cpu: 2000m
        volumeMounts:
        - name: clearglass-config
          mountPath: /etc/clearglass/settings/settings.py
          subPath: settings.py
      volumes:
      - name: clearglass-config
        configMap:
          name: clearglass-configmap
