apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    {{ .Values.productShortName }}.service: beat
  name: beat
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{ .Values.productShortName }}.service: beat
    spec:
      imagePullSecrets:
{{ toYaml .Values.image.secrets | indent 8 }}
      containers:
      - name: beat
        args:
        - bin/beat
        image: {{ .Values.image.registry }}/api:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          limits:
            memory: 250Mi
            cpu: 200m
          requests:
            memory: 125Mi
            cpu: 50m
        volumeMounts:
        - name: {{ .Values.productShortName }}-config
          mountPath: /etc/{{ .Values.productShortName }}/settings/settings.py
          subPath: settings.py
      volumes:
      - name: {{ .Values.productShortName }}-config
        configMap:
          name: {{ .Values.productShortName }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
