{{ if and .Values.prometheus.enabled .Values.prometheus.operator.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-celery
  namespace: {{ .Values.prometheus.operator.serviceMonitor.namespace }}
  labels:
{{- if .Values.prometheus.operator.serviceMonitor.selector }}
{{ toYaml .Values.prometheus.operator.serviceMonitor.selector | indent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      {{ .Values.productShortName }}.service: celery-exporter
  endpoints:
  - port: exporter
    interval: {{ .Values.prometheus.operator.serviceMonitor.interval }}
  namespaceSelector:
    any: true
{{ end }}
