apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    clearglass.service: celery-prefork
  name: celery-prefork
spec:
  replicas: 1
  template:
    metadata:
      labels:
        clearglass.service: celery-prefork
    spec:
      imagePullSecrets:
{{ toYaml .Values.image.secrets | indent 8 }}
      containers:
      - args:
        - bin/wait-all
        - bin/celery-prefork
        image: {{ .Values.image.registry }}/api:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: celery-prefork
        resources:
          requests:
            memory: 1000Mi
            cpu: 400m
          limits:
            memory: 2000Mi
            cpu: 2000m
        volumeMounts:
        - name: clearglass-config
          mountPath: /etc/clearglass/settings.py
          subPath: settings.py
      volumes:
      - name: clearglass-config
        configMap:
          name: clearglass-configmap
