apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    {{ .Values.productShortName }}.service: cilia
  name: cilia
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{ .Values.productShortName }}.service: cilia
    spec:
      imagePullSecrets:
{{ toYaml .Values.image.secrets | indent 8 }}
      containers:
      - name: cilia
        args:
        - bin/cilia
        image: {{ .Values.image.registry }}/api:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          resources:
            limits:
              memory: 150Mi
              cpu: 500m
            requests:
              memory: 80Mi
              cpu: 70m
        volumeMounts:
        - name: {{ .Values.productShortName }}-config
          mountPath: /etc/{{ .Values.productShortName }}/settings/settings.py
          subPath: settings.py
      volumes:
      - name: {{ .Values.productShortName }}-config
        configMap:
          name: {{ .Values.productShortName }}
