apiVersion: v1
kind: ConfigMap
metadata:
  name: clearglass-configmap
data:
  settings.py: |
    CORE_URI = "http{{ if .Values.http.tlsSecret }}s{{end}}://{{ .Values.http.host }}"
    JS_BUILD = False
    MAILER_SETTINGS = {
        'mail.host': "{{ .Values.smtp.host }}",
        'mail.port': "{{ .Values.smtp.port }}",
        'mail.tls': {{ if .Values.smtp.tls }}True{{ else }}False{{ end }},
        'mail.starttls': {{ if .Values.smtp.starttls }}True{{ else }}False{{ end }},
        'mail.username': "{{ .Values.smtp.username }}",
        'mail.password': "{{ .Values.smtp.password }}"
    }
    ENABLE_DEV_USERS = {{ if .Values.clearglass.enableDevUsers }}True{{ else }}False{{ end }}
