apiVersion: batch/v1
kind: Job
metadata:
  name: elasticsearch-manage
spec:
  backoffLimit: 10
  template:
    spec:
      containers:
      - args:
        - ./scripts/add_templates.py
        image: mist/elasticsearch-manage:staging
        name: elasticsearch-manage
        resources: {}
      restartPolicy: Never
