apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gocky
  labels:
    {{ .Values.productShortName }}.service: gocky
spec:
  replicas: 1
  template:
    metadata:
      labels:
        {{ .Values.productShortName }}.service: gocky
    spec:
      imagePullSecrets:
{{ toYaml .Values.image.secrets | indent 8 }}
      containers:
      - name: gocky
        image: {{ .Values.image.registry }}/gocky:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - -config
        - /etc/gocky/config.toml
        ports:
        - containerPort: 9096
        - containerPort: 9097
        volumeMounts:
        - name: gocky-config
          mountPath: /etc/gocky/config.toml
          subPath: config.toml
        resources:
          requests:
            memory: 10Mi
            cpu: 50m
          limits:
            memory: 50Mi
            cpu: 1000m
      volumes:
      - name: gocky-config
        configMap:
          name: gocky-configmap
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
