apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    {{ .Values.productShortName }}.service: hubshell
  name: hubshell
spec:
  replicas: 1
  template:
    metadata:
      labels:
        {{ .Values.productShortName }}.service: hubshell
    spec:
      imagePullSecrets:
{{ toYaml .Values.image.secrets | indent 8 }}
      containers:
      - name: hubshell
        args:
        - bin/hubshell
        image: {{ .Values.image.registry }}/api:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          requests:
            memory: 100Mi
            cpu: 10m
          limits:
            memory: 200Mi
            cpu: 1000m
        volumeMounts:
        - name: {{ .Values.productShortName }}-config
          mountPath: /etc/{{ .Values.productShortName }}/settings/settings.py
          subPath: settings.py
      volumes:
      - name: {{ .Values.productShortName }}-config
        configMap:
          name: {{ .Values.productShortName }}
