apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    {{ .Values.productShortName }}.service: landing
  name: landing
spec:
  replicas: {{ .Values.deployment.landing.replicas | default "1" }}
  template:
    metadata:
      labels:
        {{ .Values.productShortName }}.service: landing
    spec:
      imagePullSecrets:
{{ toYaml .Values.image.secrets | indent 8 }}
      containers:
      - name: landing
        args:
        - sh
        - /entry.sh
        image: {{ .Values.image.registry }}/landing:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          requests:
            memory: {{ .Values.deployment.landing.resources.requests.memory | default "20Mi" }}
            cpu: {{ .Values.deployment.landing.resources.requests.cpu | default "10m" }}
          limits:
            memory: {{ .Values.deployment.landing.resources.limits.memory | default "50Mi" }}
            cpu: {{ .Values.deployment.landing.resources.limits.cpu | default "200m" }}
