apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    clearglass.service: poller
  name: poller
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        clearglass.service: poller
    spec:
      imagePullSecrets:
{{ toYaml .Values.image.secrets | indent 8 }}
      containers:
      - args:
        - bin/wait-all
        - bin/poller
        image: {{ .Values.image.registry }}/api:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: poller
        resources:
          requests:
            memory: 100Mi
            cpu: 500m
          limits:
            memory: 200Mi
            cpu: 2000m
        volumeMounts:
        - name: clearglass-config
          mountPath: /etc/clearglass/settings.py
          subPath: settings.py
      volumes:
      - name: clearglass-config
        configMap:
          name: clearglass-configmap
