{{ range $name, $settings := $.Values.deployment.dramatiq -}}
{{ if $settings.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" $ }}-dramatiq-{{ $name }}
  labels:
    app: dramatiq-{{ $name }}
    lapp: dramatiq
    chart: {{ include "chart.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
  annotations:
    prometheus.io/path: /
    prometheus.io/port: "9191"
    prometheus.io/scrape: "true"
spec:
  replicas: {{ $settings.replicas | default "1" }}
  selector:
    matchLabels:
      release: {{ $.Release.Name }}
  template:
    metadata:
      labels:
        app: dramatiq-{{ $name }}
        lapp: dramatiq
        release: {{ $.Release.Name }}
      annotations:
        # Trigger modification of deployment & restart of pods if config changes.
        checksum/config: {{ include (print $.Template.BasePath "/main-configmap.yaml") $ | sha256sum }}
    spec:
      imagePullSecrets:
{{ toYaml $.Values.image.secrets | indent 8 }}
      containers:
      - name: dramatiq-{{ $name }}
        args:
        - bin/dramatiq
        image: {{ $.Values.image.registry }}/api:{{ $.Values.image.tag }}
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        env:
        - name: DRAMATIQ_CONTEXT
          value: "true"
        - name: prometheus_multiproc_dir
          value: /tmp/dramatiq-prometheus
        - name: dramatiq_prom_db
          value: /tmp/dramatiq-prometheus
        - name: QUEUES
          value: "{{ range $i, $q := $settings.queues }}{{ if gt $i 0 }},{{ end }}{{ $q }}{{ end }}"
        - name: dramatiq_delay_queue_prefetch
          value: "100"
        - name: DRAMATIQ_PROCESSES
          value: {{ $settings.processes | default "2" | quote}}
        - name: DRAMATIQ_THREADS
          value: {{ $settings.threads | default "8" | quote}}
        livenessProbe:
          initialDelaySeconds: 120
          periodSeconds: 60
          exec:
            command:
            - "/bin/sh"
            - "-c"
            - |
              processes=$(("${DRAMATIQ_PROCESSES}" + 2))
              running=$(ps -A | grep dramatiq | wc -l)
              if [ $processes=$running ]; then
                exit 0
              else
                exit 1
              fi
        ports:
        - containerPort: 9191
        resources:
          requests:
            memory: {{ $settings.resources.requests.memory | default "500Mi" }}
            cpu: {{ $settings.resources.requests.cpu | default "100m" }}
          limits:
            memory: {{ $settings.resources.limits.memory | default "1000Mi" }}
            cpu: {{ $settings.resources.limits.cpu | default "1000m" }}
        volumeMounts:
        - name: {{ $.Values.productShortName }}-config
          mountPath: /etc/{{ $.Values.productShortName }}/settings/settings.py
          subPath: settings.py
{{- if $settings.preemptible }}
{{- if $.Values.preemptible.tolerations }}
      tolerations:
{{ toYaml $.Values.preemptible.tolerations | indent 8 }}
{{- end }}
{{- if $.Values.preemptible.nodeAffinity }}
      affinity:
        nodeAffinity:
{{ toYaml $.Values.preemptible.nodeAffinity | indent 10 }}
{{- end }}
{{- end }}
      terminationGracePeriodSeconds: {{ $settings.gracePeriod | default 300 }}
      volumes:
      - name: {{ $.Values.productShortName }}-config
        configMap:
          name: {{ include "chart.fullname" $ }}-{{ $.Values.productShortName }}
{{- if $.Values.nodeSelector }}
      nodeSelector:
{{ toYaml $.Values.nodeSelector | indent 8 }}
{{- end }}
---
{{ end }}
{{- end }}
