{{ if and (eq .Values.elasticsearch.host "elasticsearch") (eq (toString .Values.elasticsearch.port) "9200") -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-elasticsearch
  labels:
    app: elasticsearch
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: elasticsearch
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:5.6.10
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          requests:
            memory: 2500Mi
            cpu: 50m
          limits:
            memory: 4000Mi
            cpu: 2000m
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elasticsearch
      volumes:
      - name: elasticsearch
        persistentVolumeClaim:
          claimName: {{ include "chart.fullname" . }}-elasticsearch
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
{{- end }}
