{{ if eq .Values.fdb.host "" -}}
kind: FoundationDBCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    app: fdb
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ include "chart.fullname" . }}-
spec:
  version: 6.2.11
  faultDomain:
    key: foundationdb.org/none
  processCounts:
    stateless: -1
  customParameters:
    - "knob_disable_posix_kernel_aio=1"
  persistentVolumeClaim:
    spec:
      storageClassName: ssd
      resources:
        requests:
          storage: "16G"
  podTemplate:
    spec:
      securityContext:
        fsGroup: 0
      containers:
        - name: foundationdb
          securityContext:
            runAsUser: 0
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
        - name: foundationdb-kubernetes-sidecar
          securityContext:
            runAsUser: 0
      initContainers:
        - name: foundationdb-kubernetes-init
          securityContext:
            runAsUser: 0
{{- end }}
