apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-gocky
  labels:
    app: gocky
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.toml: |
    [[http]]
    name = "influxdb"
    bind-addr = "0.0.0.0:9096"
    output = [
      {{- if .Values.influxdb.monitoring }}
      {{- if .Values.influxdb.host }}
        { name="influxdb", location = "http://{{ .Values.influxdb.host }}:{{ .Values.influxdb.port }}/write", type="influxdb"},
      {{- else }}
        { name="influxdb", location = "http://{{ include "chart.fullname" . }}-influxdb:8086/write", type="influxdb"},
      {{- end }}
      {{- end }}
      {{  if .Values.victoriametricscluster.enabled -}}
        { name="victoriametrics", location="http://{{ .Release.Name }}-vmcluster-vminsert.{{ .Release.Namespace }}.svc.cluster.local:8480/insert/0/influx/write", type="influxdb"},
      {{- else if .Values.victoriametrics.enabled -}}
        { name="victoriametrics", location="{{ .Values.victoriametrics.writeEndpoint }}", type="influxdb"},
      {{- end }}
    ]
