apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-huproxy
  labels:
    app: huproxy
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: huproxy
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: huproxy
        args:
        - /app
        - --listen
        - 0.0.0.0:8086
        env:
        - name: MONGO_URI
        {{- if .Values.mongodb.host }}
          value: mongodb://{{ .Values.mongodb.host }}{{ if .Values.mongodb.port }}:{{ .Values.mongodb.port }}{{ end }}
        {{- else }}
          value: mongodb://{{ .Release.Name }}-mongodb:27017
        {{- end }}
        - name: SECRET
          value: {{ .Values.internalKeys.secret }}
        image: mist/huproxy
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          limits:
            memory: 300Mi
            cpu: 50m
          requests:
            memory: 20Mi
            cpu: 1m
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
