apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    app: nginx
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: nginx
{{- if .Values.http.tlsSecret }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    {{- if .Values.http.http2 }}
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    {{- end }}
    {{- if .Values.http.tlsClusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.http.tlsClusterIssuer }}
    {{- end }}
{{- end }}
{{- if .Values.http.tlsAnnotations }}
{{ toYaml .Values.http.tlsAnnotations | indent 4 }}
{{- end }}
spec:
{{- if .Values.http.tlsSecret }}
  tls:
    - secretName: {{ .Values.http.tlsSecret }}
      hosts:
  {{- if .Values.http.tlsHosts }}
{{ toYaml .Values.http.tlsHosts | indent 8 }}
  {{- else }}
        - {{ .Values.http.host }}
  {{- end }}
{{- end }}
  rules:
  - host: {{ .Values.http.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "chart.fullname" . }}-nginx
            port:
              number: 80
        pathType: ImplementationSpecific
