apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-logstash
  labels:
    app: logstash
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: logstash
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
{{ toYaml .Values.image.secrets | indent 8 }}
      containers:
      - name: logstash
        env:
      {{- if .Values.elasticsearch.host }}
        - name: ELASTIC_URI
          value: http{{ if .Values.elasticsearch.tls }}s{{end}}://{{ .Values.elasticsearch.host }}:{{ .Values.elasticsearch.port }}
        - name: ELASTIC_USERNAME
          value: {{ .Values.elasticsearch.username | default "admin" }}
        - name: ELASTIC_PASSWORD
          value: {{ .Values.elasticsearch.password | default "admin" }}
      {{- else }}
        - name: ELASTIC_URI
          value: http://{{ include "chart.fullname" . }}-elasticsearch:9200
        - name: ELASTIC_USERNAME
          value: ''
        - name: ELASTIC_PASSWORD
          value: ''
      {{- end }}
        - name: RABBITMQ_HOST
          value: {{ if .Values.rabbitmq.enabled }}{{ .Release.Name }}-rabbitmq{{ else }}{{ .Values.rabbitmqExternal.host }}{{ end }}
        - name: RABBITMQ_PORT
          value: "{{ if .Values.rabbitmq.enabled }}5672{{ else }}{{ .Values.rabbitmqExternal.port }}{{ end }}"
        - name: RABBITMQ_USERNAME
          value: {{ if .Values.rabbitmq.enabled }}{{ .Values.rabbitmq.auth.username }}{{ else }}{{ .Values.rabbitmqExternal.username }}{{ end }}
        - name: RABBITMQ_PASSWORD
          value: {{ if .Values.rabbitmq.enabled }}{{ .Values.rabbitmq.auth.password }}{{ else }}{{ .Values.rabbitmqExternal.password }}{{ end }}
        - name: INFLUXDB_HOST
          value: {{ if .Values.influxdb.host }}{{ .Values.influxdb.host }}{{ else }}{{ include "chart.fullname" . }}-influxdb{{ end }}
        - name: INFLUXDB_PORT
          value: "{{ if .Values.influxdb.host }}{{ .Values.influxdb.port }}{{ else }}8086{{ end }}"
        image: {{ .Values.image.registry }}/logstash:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          requests:
            memory: 500Mi
            cpu: 100m
          limits:
            memory: 700Mi
            cpu: 1000m
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
