{{ if and (eq .Values.mongodb.host "mongodb") (eq (toString .Values.mongodb.port) "27017") -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-mongodb
  labels:
    app: mongodb
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongodb
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: mongodb
        image: mongo:3.2
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          requests:
            memory: 200Mi
            cpu: 400m
          limits:
            memory: 400Mi
            cpu: 1000m
        volumeMounts:
        - mountPath: /data/db
          name: mongodb
      volumes:
      - name: mongodb
        persistentVolumeClaim:
          claimName: {{ include "chart.fullname" . }}-mongodb
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
{{- end }}
