{{ range $name, $settings := $.Values.deployment.scheduler -}}
{{ if $settings.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" $ }}-scheduler-{{ $name }}
  labels:
    app: scheduler-{{ $name }}
    chart: {{ include "chart.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  replicas: {{ $settings.replicas | default "1" }}
  selector:
    matchLabels:
      release: {{ $.Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: scheduler-{{ $name }}
        release: {{ $.Release.Name }}
      annotations:
        # Trigger modification of deployment & restart of pods if config changes.
        checksum/config: {{ include (print $.Template.BasePath "/main-configmap.yaml") $ | sha256sum }}
    spec:
      imagePullSecrets:
{{ toYaml $.Values.image.secrets | indent 8 }}
      containers:
      - name: scheduler
        args:
        - bin/scheduler
        image: {{ $.Values.image.registry }}/api:{{ $.Values.image.tag }}
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        env:
        - name: SCHEDULES
          value: "{{ range $i, $q := $settings.schedules }}{{ if gt $i 0 }},{{ end }}{{ $q }}{{ end }}"
        - name: INTERNAL_KEYS_CILIA
          valueFrom:
            secretKeyRef:
              name: {{ include "chart.fullname" $ }}-internal-keys-secret
              key: cilia
              optional: false
        - name: INTERNAL_KEYS_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "chart.fullname" $ }}-internal-keys-secret
              key: secret
              optional: false
        - name: INTERNAL_KEYS_SIGN
          valueFrom:
            secretKeyRef:
              name: {{ include "chart.fullname" $ }}-internal-keys-secret
              key: sign
              optional: false
        resources:
          requests:
            memory: {{ $settings.resources.requests.memory | default "100Mi" }}
            cpu: {{ $settings.resources.requests.cpu | default "10m" }}
          limits:
            memory: {{ $settings.resources.limits.memory | default "400Mi" }}
            cpu: {{ $settings.resources.limits.cpu | default "1000m" }}
        volumeMounts:
        - name: {{ $.Values.productShortName }}-config
          mountPath: /etc/{{ $.Values.productShortName }}/settings/settings.py
          subPath: settings.py
        {{- if $.Values.vault.deploy }}
        - name: {{ $.Values.vault.mistSecretName }}
          mountPath: /approle
        {{- end }}
      volumes:
      - name: {{ $.Values.productShortName }}-config
        configMap:
          name: {{ include "chart.fullname" $ }}-{{ $.Values.productShortName }}
      {{- if $.Values.vault.deploy }}
      - name: {{ $.Values.vault.mistSecretName }}
        secret:
          secretName: {{ $.Values.vault.mistSecretName }}
          items:
            - key: roleId
              path: role_id
            - key: secretId
              path: secret_id
      {{- end }}
{{- if $.Values.nodeSelector }}
      nodeSelector:
{{ toYaml $.Values.nodeSelector | indent 8 }}
{{- end }}
---
{{ end }}
{{- end }}