{{- if .Values.vault.deploy }}

{{- $roleId := uuidv4 | b64enc | quote }}
{{- $secretId := uuidv4 | b64enc | quote }}

{{- with (index .Values.vault.server.volumes 1) }}
{{- $secret := (lookup "v1" "Secret" $.Release.Namespace .secret.secretName) }}
{{- if $secret }}
{{- $roleId = index $secret.data "roleId" }}
{{- $secretId = index $secret.data "secretId" }}
{{- end -}}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
{{- with (index .Values.vault.server.volumes 1) }}
  name: {{ .secret.secretName }}
{{- end }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  roleId: {{ $roleId }}
  secretId: {{ $secretId }}
{{- end }}
