[[http]]
name = "example-http"
bind-addr = "0.0.0.0:9096"
output = [
    { name="local1", location = "http://influxdb:8086/write" },
]


[[beringei]]
name = "example-beringei"
bind-addr = "0.0.0.0:9097"
amqp-url = "amqp://guest:guest@rabbitmq:5672/"
beringei-update-url = "http://beringei-http:9990/update"
output = [
    { name="local1", location="beringei-http:9990"}
]
