name: mist-ce
description: A Helm Chart for Mist CE.
version: 0.0.0
appVersion: "0.0.0"
apiVersion: v1
icon: https://raw.githubusercontent.com/mistio/mist.ui/master/assets/app-icon-32.png
dependencies:
  - alias: rabbitmq
    condition: rabbitmq.deploy
    repository: https://charts.bitnami.com/bitnami
    name: rabbitmq
    version: 9.1.4
    # RabbitMQ version: 3.9.18
  - alias: mongodb
    condition: mongodb.deploy
    repository: https://charts.bitnami.com/bitnami
    name: mongodb
    version: 10.31.5
    # MongoDB version: 4.4.11
  - alias: victoriametrics
    name: victoria-metrics-cluster
    condition: victoriametrics.deploy
    repository: https://victoriametrics.github.io/helm-charts/
    version: 0.8.24
  - alias: vault
    name: vault
    condition: vault.deploy
    repository: https://helm.releases.hashicorp.com
    version: 0.20.1
    # Vault version: 1.10.3
