name: mist-ce
description: A Helm Chart for Mist CE.
version: $CHART_VERSION
appVersion: "$CHART_VERSION"
apiVersion: v1
icon: https://raw.githubusercontent.com/mistio/mist.ui/master/assets/app-icon-32.png
dependencies:
  - alias: rabbitmq
    condition: rabbitmq.deploy
    repository: https://charts.bitnami.com/bitnami
    name: rabbitmq
    version: 8.15.0
  - alias: mongodb
    condition: mongodb.deploy
    repository: https://charts.bitnami.com/bitnami
    name: mongodb
    version: 10.0.5
  - alias: victoriametricscluster
    name: victoria-metrics-cluster
    condition: victoriametricscluster.enabled
    repository: https://victoriametrics.github.io/helm-charts/
    version: 0.8.24